name: Deploy to EC2

on:
  push:
    branches: [master]  # Change to 'main' if your branch is 'main'

jobs:
  deploy:
    name: Deploy App on EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd Terraform_Docker_App || git clone https://github.com/<your-username>/Terraform_Docker_App.git && cd Terraform_Docker_App
            git pull origin master
            pkill -f uvicorn || true
            pkill -f npm || true
            cd backend
            pip3 install -r requirements.txt
            nohup uvicorn app.main:app --host 0.0.0.0 --port 5000 &
            cd ../frontend
            npm install
            npm run build
            nohup npm start &
          EOF
